primer commit Calculadora
facu-rodriguez/react-calculator-app pull request #2
Opened 2020-08-05 20:14 UTC by facu-rodriguez

## Summary

Incorporación de 3 nuevos componentes (Botones, Button, Input) que son la base de la aplicación y hasta el momento, lo único que esta contiene. Además le definí todos los estilos a cada componente y utilicé MediasQueries para el responsive.

## Test Cases
-Realizar operaciones (Suma, resta, multiplicación, división).
-Borrar toda la expresión o borrar un caracter.

## Screenshots
![calculadora](https://user-images.githubusercontent.com/68086087/89459052-7212cb80-d73e-11ea-90e2-cff04d16059a.png)

## Jira Card
-

2020-08-06 14:59 UTC, glipina requested changes
Check the ifs that we talked about.
Tidy up the code, delete logs and comments.
If possible fix the styles and use display flex.

2020-08-06 15:28 UTC, tbecerro requested changes
Hi @facu-rodriguez, really good job!! only some comments

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Botones/index.js
> +    console.log(this);
delete this

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Botones/index.js
> +];
create a file (constants.js) and move this also rename "BUTTONS_CONFIG"

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Botones/index.js
> +  { className: styles.borrarTodo, value: 'C', text: 'C' },
remember that all code must be in English  so rename `styles.borrarTodo` for `styles.deleteAll`

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Botones/style.module.scss
> +//@media #{$mobile} {}
delete this

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Botones/style.module.scss
> +  }
?

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Buton/index.js
> +  */
delete this

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Buton/index.js
> +
delete this

2020-08-06 15:28 UTC, tbecerro commented on src/app/components/Input/index.js
> +    console.log(this.props);
delete this

2020-08-06 15:28 UTC, tbecerro commented on src/scss/variables/_mediaQueries.scss
> +$small-mobile: 'only screen and (max-width : 500px)'; //cambie 361px por 500px
why?

2020-08-14 16:35 UTC, facu-rodriguez commented
No está todavía configurada la mediaQuery del componente Trace para mobile

2020-08-14 19:51 UTC, facu-rodriguez commented
@tbecerro @glipina Ahí subí el último commit, la calculadora ya es 100% responsive

2020-08-20 12:17 UTC, tbecerro requested changes
Hi @facu-rodriguez, good job! only check this : 
![boom](https://user-images.githubusercontent.com/45640698/90768975-e4021d80-e2c5-11ea-961f-f376f52b3a47.gif)

2020-08-20 22:44 UTC, facu-rodriguez commented
Hi @tbecerro bug fix!

2020-08-21 14:29 UTC, tbecerro requested changes
Hi @facu-rodriguez  check this : 
![bombom](https://user-images.githubusercontent.com/45640698/90901601-8c38e480-e3a1-11ea-8c53-88d32ab603e5.gif)

2020-08-21 14:47 UTC, facu-rodriguez commented
Hi @tbecerro I've already fixed the bug

2020-08-21 15:24 UTC, tbecerro approved these changes

2020-08-21 15:38 UTC, glipina approved these changes

2020-08-25 15:30 UTC, closed without merging