Router branch
facu-rodriguez/react-calculator-app pull request #3
Opened 2020-08-18 15:54 UTC by facu-rodriguez

## Summary

Implementación de React-Router.
Ahora los componentes generales de mi App se renderizan dentro de Screens y no en el index.js general.

## Test Cases

-Escribir en la url 'trace' de diferentes maneras (p.e 'TrACe'). Esto debería llegar a '/trace'
-Escribir en la url cualquier cosa distinta a 'trace'. Esto debería llegar a '/' que corresponde a HOME.

## Screenshots

![image](https://user-images.githubusercontent.com/68086087/90535722-982e6780-e151-11ea-98ff-7f2c7a15cc33.png)
![image](https://user-images.githubusercontent.com/68086087/90535773-a1b7cf80-e151-11ea-8192-a99e6a6ba7ef.png)

## Jira Card

Rutas en la APP

2020-08-20 12:49 UTC, tbecerro requested changes
Hi @facu-rodriguez, good job!! check when I save value in home not save: 
![historyCalc](https://user-images.githubusercontent.com/45640698/90771977-67257280-e2ca-11ea-8017-b35f89923af2.gif)

2020-08-21 13:58 UTC, facu-rodriguez commented
Hi @tbecerro I´ve already solved the bug and also I solved some style issues with the trace button

2020-08-21 14:40 UTC, tbecerro approved these changes

2020-08-21 15:39 UTC, glipina approved these changes

2020-08-25 15:30 UTC, closed without merging