Integracion api
facu-rodriguez/react-calculator-app pull request #4
Opened 2020-08-20 21:05 UTC by facu-rodriguez

## Summary

Integración de Servicios a la App. 
Utilicé redux-recompose.
Las funcionalidades de la Aplicación son exactamente las mismas, nada mas que ahora, según el tipo de acción que se quiera ejecutar, se comunica un con servicio (que es un mock-up) y realiza distintos métodos.
En este caso trabajé con los métodos GET, POST, PUT y DELETE.
El usuario será notificado con una alerta, que va a contener el mensaje que devuelve el servicio al usuario cada vez que ejecuté una acción.

## Test Cases

[Change!] Add test cases or useful information for reviewers to test and check pull request changes.

## Screenshots

[Change!] Show the screenshots of the views you modified.
![image](https://user-images.githubusercontent.com/68086087/90825590-8692be80-e30f-11ea-99f6-f3c812a0e27b.png)
![image](https://user-images.githubusercontent.com/68086087/90825616-8db9cc80-e30f-11ea-9b9c-bc262f97f16c.png)
![image](https://user-images.githubusercontent.com/68086087/90825650-96aa9e00-e30f-11ea-931b-4d67c9efbfa4.png)

## Jira Card

Agregando servicios a la APP

2020-08-21 15:17 UTC, tbecerro requested changes
Hi @facu-rodriguez really good job!! only some comments

2020-08-21 15:17 UTC, tbecerro commented on src/redux/traceExpression/actions.js
> +      let answ = response.data.map(i => i.message);
why this ?

2020-08-21 15:17 UTC, tbecerro commented on src/redux/traceExpression/actions.js
> +    const traceExpressionArray = getState().traceExpression;
change this for `const traceExpressionArray = getState().traceExpression.traceExpression;`

2020-08-21 15:21 UTC, tbecerro requested changes

2020-08-21 15:21 UTC, tbecerro commented on src/redux/traceExpression/actions.js
> +    ['DELETE_ALL', 'HANDLE_TRACE_EXPRESSION']
why 'DELETE_ALL' is here?

2020-08-21 15:22 UTC, facu-rodriguez commented on src/redux/traceExpression/actions.js
> +      let answ = response.data.map(i => i.message);
I create that var because I want to receive the service message to show it to the user

2020-08-21 15:38 UTC, glipina requested changes
This pr is mostly OK. I think you still have some issues with name consistency between your components, your filenames, ect. so pay attention to this issues when you start working on productive code, however you have improved a lot between the first pr and this one the code here is tidier and easier to read. I left you some code style comments.

2020-08-21 15:38 UTC, glipina commented on src/app/components/Buton/style.module.scss
> +
There is no need to have empty files

2020-08-21 15:38 UTC, glipina commented on src/app/components/RenderButons/style.module.scss
> +}
This can go inside of active as a pseudoclass like: 
`&:active {your class}`

2020-08-21 15:38 UTC, glipina commented on src/app/index.js
> +    switch (value) {
Move this functions to a utils file.

2020-08-21 15:46 UTC, facu-rodriguez commented on src/redux/traceExpression/actions.js
> +    const traceExpressionArray = getState().traceExpression;
Solved!

2020-08-21 15:46 UTC, facu-rodriguez commented on src/redux/traceExpression/actions.js
> +    ['DELETE_ALL', 'HANDLE_TRACE_EXPRESSION']
Solved!

2020-08-21 17:44 UTC, facu-rodriguez commented
Hi @tbecerro @glipina all my code is here now! Including the last comments you made.

2020-08-24 14:12 UTC, tbecerro approved these changes

2020-08-25 15:29 UTC, merged